app/cake/config/routes.php
<?php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    $routes->addExtensions([
        'pdf',
        'json',
        'txt',
        'svg',
        'ndjson',

        // Linked data
        'xml',
        'rdf',
        'ttl',
        'nt',
        'jsonld',

        // Tables
        'csv',
        'tsv',
        'xlsx',

        // Bibliographies
        'bib',
        'ris'
    ]);

    // Admin prefix
    Router::prefix('admin', function ($routes) {

        // Pages for each controller
        $routes->connect('/:controller', ['action' => 'index']);
        $routes->connect('/:controller/edit/*', ['action' => 'edit']);
        $routes->connect('/:controller/add/*', ['action' => 'add']);
        $routes->connect('/:controller/delete/*', ['action' => 'delete']);
        $routes->connect('/:controller/export/*', ['action' => 'export']);
        $routes->connect('/:controller/*', ['action' => 'view']);

        // Dashboard
        $routes->connect('/dashboard', ['controller' => 'Home', 'action' => 'dashboard']);

        // Routes for Admin journals dashboard.
        $routes->connect('/periods/token-lists', ['controller' => 'Periods', 'action' => 'tokenLists']);
        $routes->connect('/periods/:id/token-list/:kind', ['controller' => 'Periods', 'action' => 'tokenList'])
            ->setPass(['id', 'kind']);
        $routes->connect('/articles/link/publications', ['controller' => 'Articles', 'action' => 'link_publications']);
        $routes->connect('/api/view/link/:article/:publication', ['controller' => 'Articles', 'action' => 'view_link']);
        $routes->connect('/api/link/:article/:publication', ['controller' => 'Articles', 'action' => 'complete_link']);
        $routes->connect('/api/view/links/:id/all/:type', ['controller' => 'Articles', 'action' => 'view_all_article_links']);
        $routes->connect('/api/unlink/:article/:publication', ['controller' => 'Articles', 'action' => 'complete_unlink']);
        $routes->connect('/api/get/:id/:type', ['controller' => 'Articles', 'action' => 'get_article_by_id']);
        $routes->connect('/api/suggest/:key/:type', ['controller' => 'Articles', 'action' => 'link_suggest']);

        // Routes for Journals display at admin dashboard.
        $routes->connect('/articles/add', ['controller' => 'Articles', 'action' => 'add']);
        $routes->connect('/articles/add/:type', ['controller' => 'Articles', 'action' => 'add'], ['_name' => 'addSpecific'])
            ->setPass(['type']);
        $routes->connect('/articles/edit/:type/:article', ['controller' => 'Articles', 'action' => 'edit'])
            ->setPass(['type', 'article']);
        $routes->connect('/articles/delete/:type/:article', ['controller' => 'Articles', 'action' => 'delete'])
            ->setPass(['type', 'article']);
        $routes->post('/articles/preview', ['controller' => 'Articles', 'action' => 'preview']);

        $routes->connect('/articles/convert-bibtex', ['controller' => 'Articles', 'action' => 'convertBibtex']);
        $routes->connect('/articles/convert-latex', ['controller' => 'Articles', 'action' => 'convertLatex']);

        // Routes for Admin Author Ajax.
        $routes->connect('/authors/search/:author', ['controller' => 'Authors', 'action' => 'author_search_ajax'])
            ->setPass(['author']);
        $routes->connect('/authors/add/:author', ['controller' => 'Authors', 'action' => 'add_author_ajax'])
            ->setPass(['author']);

        $routes->connect('/uploads/geturl', ['controller' => 'Uploads ', 'action' => 'geturl']);
        $routes->connect('/uploads/dashboard', ['controller' => 'Uploads ', 'action' => 'dashboard']);

        // Routes for Admin CdliTablet
        $routes->connect('/cdli-tablet/delete-all', ['controller' => 'CdliTablet', 'action' => 'deleteAll']);

        // Route for Retired Artifacts Index
        $routes->connect('/artifacts/retired', ['controller' => 'Artifacts', 'action' => 'retired']);

        // Assets
        $routes->connect('/artifact-assets/missing-files', ['controller' => 'ArtifactAssets', 'action' => 'missingFiles']);
        $routes->connect('/artifact-assets/update-index', ['controller' => 'ArtifactAssets', 'action' => 'updateIndex']);

        //Route for Add/Edit Featured Seals
        $routes->connect('/artifacts/featured-seals/add', ['controller' => 'Artifacts' , 'action' => 'featuredSealsAdd']);
        $routes->connect('/artifacts/featured-seals/edit/:id', ['controller' => 'Artifacts' , 'action' => 'featuredSealsEdit'], ['pass' => ['id']]);

        //Route for Seal Chemistry
        $routes->connect('/artifacts/seal-chemistry/add', ['controller' => 'Artifacts' , 'action' => 'sealChemistryAdd']);
        //$routes->connect('/artifacts/seal-chemistry/edit/:id', ['controller' => 'Artifacts' , 'action' => 'sealChemistryEdit'],['pass' => ['id']]);
        $routes->connect('/artifacts/calibration/add', ['controller' => 'Artifacts' , 'action' => 'calibrationAdd']);

        // Other routes
        $routes->connect('/users/forgot-password/*', ['controller' => 'Users', 'action' => 'forgotPassword']);

        $routes->fallbacks('DashedRoute');
    });

    // Docs
    $routes->connect('/docs/audience/*', ['controller' => 'Docs', 'action' => 'audience']);
    $routes->connect('/docs/category/*', ['controller' => 'Docs', 'action' => 'category']);
    $routes->connect('/docs/:document/:version', ['controller' => 'Docs', 'action' => 'otherDocuments'])
        ->setPatterns(['document' => 'schema|vocab'])
        ->setPass(['document', 'version']);

    // Permalinks
    $routes->connect('/:id', ['controller' => 'Artifacts', 'action' => 'resolve'])
        ->setPatterns(['id' => '[PQS]\d{6}|S\d{6}\.\d'])
        ->setPass(['id']);
    $routes->connect('/:id', ['controller' => 'Search', 'action' => 'resolve'])
        ->setPatterns(['id' => '([PQS]\d{6}|S\d{6}\.\d)(,([PQS]\d{6}|S\d{6}\.\d))+'])
        ->setPass(['id']);

    // Artifacts (see also controllers below)
    $routes->connect('/artifact-assets/authorize', ['controller' => 'ArtifactAssets', 'action' => 'authorize']);
    $routes->connect('/artifact-assets/resolve', ['controller' => 'ArtifactAssets', 'action' => 'resolve']);
    $routes->connect('/artifacts/:id/images', ['controller' => 'Artifacts', 'action' => 'images'])->setPass(['id']);
    $routes->connect('/artifacts/:id/reader/:image', ['controller' => 'Artifacts', 'action' => 'reader'])->setPass(['id', 'image']);
    $routes->connect('/artifacts/:id/annotations/:image', ['controller' => 'Artifacts', 'action' => 'annotations'])->setPass(['id', 'image']);
    $routes->connect(
        '/artifacts/:id/history/:type',
        ['controller' => 'Artifacts', 'action' => 'history']
    )->setPass(['id', 'type'])->setPersist(['id', 'type']);
    $routes->connect(
        '/artifacts/:id/inscription',
        ['controller' => 'Artifacts', 'action' => 'resolveInscription']
    )->setPass(['id']);
    $routes->connect(
        '/artifacts/:id/inscription/:format',
        ['controller' => 'Artifacts', 'action' => 'resolveInscription'],
        ['_name' => 'resolveInscriptionWithFormat']
    )->setPass(['id']);
    $routes->connect('/artifacts/composites', ['controller' => 'Artifacts' , 'action' => 'composites']);
    $routes->connect('/artifacts/composites/:compositetype', ['controller' => 'Artifacts' , 'action' => 'composites'], ['pass' => ['compositetype']]);
    $routes->connect('/artifacts/composites-score/:compositenumber', ['controller' => 'Artifacts' , 'action' => 'compositesScore'], ['pass' => ['compositenumber']]);
    $routes->connect('/artifacts/seals', ['controller' => 'Artifacts' , 'action' => 'seals']);
    $routes->connect('/artifacts/:id/chemistry/csv', ['controller' => 'Artifacts', 'action' => 'downloadChemistryCSV'], ['pass' => ['id']]);
    $routes->connect('/artifacts/:id/:artifactId/delete', ['controller' => 'Artifacts', 'action' => 'deleteChemistry'], ['pass' => ['id','artifactId']]);
    $routes->connect('/artifacts/seal-chemistry/add', ['controller' => 'Artifacts' , 'action' => 'sealChemistryAdd']);
    $routes->connect('/artifacts/seal-chemistry/edit/:id', ['controller' => 'Artifacts' , 'action' => 'sealChemistryEdit'], ['pass' => ['id']]);
    $routes->connect('/artifact-asset-annotations/delete/:id', ['controller' => 'ArtifactAssetAnnotations', 'action' => 'delete'])->setPass(['id']);

    // Publications
    $routes->connect('/publications/merge', ['controller' => 'Publications', 'action' => 'merge']);
    $routes->connect('/publications/search', ['controller' => 'Publications', 'action' => 'search']);
    $routes->connect('/publications/upload', ['controller' => 'Publications', 'action' => 'upload']);
    $routes->connect('/publications/delete/:id', ['controller' => 'Publications', 'action' => 'delete'])->setPass(['id']);

    // Search API
    $routes->connect('/search/token-list/:kind', ['controller' => 'Search', 'action' => 'tokenList'])->setPass(['kind']);

    // Update events
    $routes->connect('/update-events/approve/:id', ['controller' => 'UpdateEvents', 'action' => 'approve'])->setPass(['id']);
    $routes->connect('/update-events/submit/:id', ['controller' => 'UpdateEvents', 'action' => 'submit'])->setPass(['id']);
    $routes->connect('/update-events/decline/:id', ['controller' => 'UpdateEvents', 'action' => 'decline'])->setPass(['id']);
    $routes->connect('/update-events/delete/:id', ['controller' => 'UpdateEvents', 'action' => 'delete'])->setPass(['id']);
    $routes->connect('/update-events/cancel', ['controller' => 'UpdateEvents', 'action' => 'cancel']);

    // Articles
    $routes->connect('/articles/:type', ['controller' => 'Articles', 'action' => 'index'])->setPass(['type']);
    $routes->connect('/articles/:type/:id', ['controller' => 'Articles', 'action' => 'view'])->setPass(['type', 'id']);

app/cake/src/Model/Table/SponsorsTable.php
<?php // phpcs:ignore SlevomatCodingStandard.TypeHints.DeclareStrictTypes.DeclareStrictTypesMissing

namespace App\Model\Table;

use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Sponsor Model
 *
 * @property \App\Model\Table\SponsorTypesTable&\Cake\ORM\Association\BelongsTo $SponsorTypes
 * @method \App\Model\Entity\Sponsor newEmptyEntity()
 * @method \App\Model\Entity\Sponsor newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Sponsor[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Sponsor get($primaryKey, $options = [])
 * @method \App\Model\Entity\Sponsor findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Sponsor patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Sponsor[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Sponsor|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Sponsor saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Sponsor[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Sponsor[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Sponsor[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Sponsor[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 */
class SponsorsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('sponsors');
        $this->setDisplayField('sponsor');
        $this->setPrimaryKey('id');

        $this->belongsTo('SponsorTypes', [
            'foreignKey' => 'sponsor_type_id',
            'joinType' => 'INNER',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->nonNegativeInteger('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('sponsor')
            ->requirePresence('sponsor', 'create')
            ->notEmptyString('sponsor');
        $validator
            ->scalar('url')
            ->requirePresence('url', 'create')
            ->notEmptyString('url');

        $validator
            ->scalar('contribution')
            ->requirePresence('contribution', 'create')
            ->allowEmptyString('contribution');

        $validator
            ->scalar('sequence')
            ->maxLength('sequence', 100)
            ->requirePresence('sequence', 'create')
            ->allowEmptyString('sequence');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn(['sponsor_type_id'], 'SponsorTypes'), ['errorField' => 'sponsor_type_id']);

        return $rules;
    }
}

app/cake/src/Controller/Admin/SponsorsController.php
<?php
declare(strict_types=1);

namespace App\Controller\Admin;

use App\Controller\AppController;
use App\Model\Entity\Sponsor;

/**
 * @property \App\Model\Table\SponsorsTable $Sponsors
 * @method \App\Model\Entity\Sponsor[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class SponsorsController extends AppController
{
    /**
     * @return \Cake\Http\Response|null
     */
    public function add()
    {
        $sponsor = $this->Sponsors->newEmptyEntity();

        return $this->_handleAddEdit($sponsor);
    }

    /**
     * @param string|null $id
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException
     */
    public function edit($id = null)
    {
        $sponsor = $this->Sponsors->get($id);

        return $this->_handleAddEdit($sponsor);
    }

    /**
     * @param \App\Model\Entity\Sponsor $sponsor
     * @return \Cake\Http\Response|null
     */
    private function _handleAddEdit(Sponsor $sponsor)
    {
        if ($this->getRequest()->is(['patch', 'post', 'put'])) {
            $sponsor = $this->Sponsors->patchEntity($sponsor, $this->getRequest()->getData());

            if ($this->Sponsors->save($sponsor)) {
                $image = $this->getRequest()->getData('image_upload');
                $newImage = $image !== null && $image->getError() !== \UPLOAD_ERR_NO_FILE;
                $deleteImage = $this->getRequest()->getData('image_delete', '0') === '1';

                if ($newImage || $deleteImage) {
                    foreach ($sponsor->getImagePaths() as $file) {
                        unlink(realpath($file));
                    }
                }

                if ($newImage) {
                    $filename = $image->getClientFilename();
                    $extension = pathinfo($filename, PATHINFO_EXTENSION);
                    $filename = Sponsor::IMAGE_FILE_PREFIX . "$sponsor->id.$extension";
                    $image->moveTo($filename);
                }

                $this->Flash->success(__('The sponsor has been saved.'));
            } else {
                $this->Flash->error(__('The sponsor could not be saved. Please, try again.'));
            }

            if ($sponsor->has('id')) {
                return $this->redirect(['prefix' => false, 'action' => 'view', $sponsor->id]);
            } else {
                return $this->redirect(['prefix' => false, 'action' => 'index']);
            }
        }

        $sponsorTypes = $this->Sponsors->SponsorTypes->find('list');
        $this->set('sponsor', $sponsor);
        $this->set('sponsorTypes', $sponsorTypes);
        $this->render('edit');
    }

    /**
     * @param string|null $id
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException
     */
    public function delete($id = null)
    {
        $this->getRequest()->allowMethod(['post', 'delete']);

        $sponsor = $this->Sponsors->get($id);
        if ($this->Sponsors->delete($sponsor)) {
            foreach ($sponsor->getImagePaths() as $file) {
                unlink(realpath($file));
            }

            $this->Flash->success(__('The sponsor has been deleted.'));
        } else {
            $this->Flash->error(__('The sponsor could not be deleted. Please, try again.'));
        }

        return $this->redirect(['prefix' => false, 'action' => 'index']);
    }
}

app/cake/templates/Sponsors/index.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\sponsor[]|\Cake\Collection\CollectionInterface $sponsors
 * @var \App\Model\Entity\sponsor[]|\Cake\Collection\CollectionInterface $sponsor_types
 * @var bool $isAdmin
 */
use Cake\Routing\Router;
?>

<main class="container text-left">
    <div class="d-flex justify-content-between align-items-end mb-2">
        <h1 class="display-3 header-txt text-left"><?= __('Sponsors') ?></h1>
        <?= $this->element('addButton', ['access_granted' => $isAdmin]) ?>
    </div>
    <p class="text-justify page-summary-text mt-4">Over the years, CDLI has attracted support from various institutions and groups which have propelled the initiative in the establishment of state-of-the-art solutions in the areas of digitization, digital preservation, digital sustainability, cultural heritage access, cuneiform studies / Assyriology, social history, history of science, philology, and computational linguistics.</p>

    <h2>Categories</h2>
    <p>Click on a category to see the associated list of sponsors.</p>
    <div class="row">
        <?php foreach ($sponsor_types as $sponsor_type): ?>
            <div class="col">
                <?= $this->Html->link($sponsor_type->sponsor_type, '#' . $sponsor_type->id) ?>
            </div>
        <?php endforeach; ?>
    </div>

    <div>
        <?php foreach ($sponsor_types as $sponsor_type) :?>
            <h3 id="<?= $sponsor_type->id ?>" class="mb-3 mt-3"><?= $sponsor_type->sponsor_type ?></h3>
            <div class="row row-cols-1 row-cols-md-4 staff-row">
                <?php foreach ($sponsors as $sponsor): ?>
                    <?php if ($sponsor->sponsor_type_id == $sponsor_type->id): ?>
                        <div class="col-sm-3 mb-4">
                            <div class="card mb-4 border border-secondary p-3 h-100">
                                <?php if ($isAdmin): ?>
                                    <?= $this->Html->image('/images/edit.svg', [
                                        'alt' => 'Edit',
                                        'url' => ['prefix' => 'Admin', 'action' => 'edit', $sponsor->id],
                                        'title' => 'Edit',
                                        'class' => 'pull-right'
                                    ]) ?>
                                <?php endif; ?>
                                <div class="card-header d-flex h-100">
                                    <p class="my-0 font-weight-normal flex-grow-1">
                                        <span class="font-weight-bold">
                                            <?= $this->Html->link(
                                                $sponsor->sponsor,
                                                ['controller' => 'Sponsors', 'action' => 'view', $sponsor->id]
                                            ) ?>
                                        </p>
                                </div>

                                 <div class="card-body">
                                    <?= $this->Html->image($sponsor->getImage(), ['class' => 'w-100']) ?>
                                 </div>
                             </div>
                         </div>
                    <?php endif; ?>
                <?php endforeach; ?>
             </div>
         <?php endforeach; ?>
    </div>
</main>

<?= $this->element('citeBottom') ?>
<?= $this->element('citeButton') ?>

<button class="p-0 mt-5 btn d-flex align-items-center justify-content-between mx-auto wide-btn">
    <a href="#" class="text-dark btn wide-btn">
        Back to top
        <span class="fa fa-long-arrow-up ml-2" aria-hidden="true"></span>
    </a>
</button>

app/cake/templates/Sponsors/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Sponsor $sponsor
 * @var bool $isAdmin
 */
?>

<div class="text-left">
    <h1>
        <?= __('Sponsor') ?>: <?= h($sponsor->sponsor) ?>
        <?php if ($isAdmin): ?>
            <?= $this->Html->link(
                __('Edit'),
                ['prefix' => 'Admin', 'action' => 'edit', $sponsor->id],
                ['escape' => false , 'class' => "btn cdli-btn-blue pull-right", 'title' => 'Edit']
            ) ?>
        <?php endif; ?>
    </h1>

    <p><em><?= h($sponsor->sponsor_type->sponsor_type) ?></em></p>

    <hr>

    <div class="row">
        <div class="col-lg-10 col-md-8 col-12 mb-3">
            <div><?= $sponsor->contribution ?></div>
            <a href="<?= $sponsor->url ?>">Visit the home page of <?= h($sponsor->sponsor) ?>.</a>
        </div>
        <div class="col-lg-2 col-md-4 col-12 mb-3">
            <?= $this->Html->image($sponsor->getImage(), ['class' => 'mw-100']) ?>
        </div>
    </div>
</div>

<?= $this->element('citeBottom') ?>
<?= $this->element('citeButton') ?>